### ISSUE TITLE
soma_workflow should create the transfered_files directory at startup when it doesn't exist

### ISSUE THREAD

**Issue by denisri** [brainvisa/testbidon#255]
---

Author Name: **Lefranc, Sandrine** (Lefranc, Sandrine)
Original Redmine Issue: 9152, https://bioproj.extra.cea.fr/redmine/issues/9152
Original Date: 2014-01-09

---

```python -m soma_workflow.start_workflow_engine sl236442@gabriel workflow_engine_sl236442
Traceback (most recent call last):
  File "/i2bm/brainvisa/CentOS-5.3-x86_64/python-2.7.3/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/i2bm/brainvisa/CentOS-5.3-x86_64/python-2.7.3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sl236442/brainvisa/build/trunk/python/soma_workflow/start_workflow_engine.py", line 245, in <module>
    main(resource_id, engine_name)
  File "/home/sl236442/brainvisa/build/trunk/python/soma_workflow/start_workflow_engine.py", line 178, in main
    config)
  File "/home/sl236442/brainvisa/build/trunk/python/soma_workflow/start_workflow_engine.py", line 44, in __init__
    config)
  File "/home/sl236442/brainvisa/build/trunk/python/soma_workflow/engine.py", line 1118, in __init__
    queue_limits=config.get_queue_limits())
  File "/home/sl236442/brainvisa/build/trunk/python/soma_workflow/engine.py", line 650, in __init__
    self._user_id = self._database_server.register_user(user_login)
  File "/i2bm/brainvisa/CentOS-5.3-x86_64/python-2.7.3/lib/python2.7/site-packages/Pyro/core.py", line 384, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/i2bm/brainvisa/CentOS-5.3-x86_64/python-2.7.3/lib/python2.7/site-packages/Pyro/core.py", line 459, in _invokePYRO
    return self.adapter.remoteInvocation(name, Pyro.constants.RIF_VarargsAndKeywords, vargs, kargs)
  File "/i2bm/brainvisa/CentOS-5.3-x86_64/python-2.7.3/lib/python2.7/site-packages/Pyro/protocol.py", line 440, in remoteInvocation
    return self._remoteInvocation(method, flags, *args)
  File "/i2bm/brainvisa/CentOS-5.3-x86_64/python-2.7.3/lib/python2.7/site-packages/Pyro/protocol.py", line 501, in _remoteInvocation
    answer.raiseEx()
  File "/i2bm/brainvisa/CentOS-5.3-x86_64/python-2.7.3/lib/python2.7/site-packages/Pyro/errors.py", line 73, in raiseEx
    raise self.excObj
OSError: [Errno 2] No such file or directory: '/home/sl236442/.soma-workflow/transfered_files/sl236442_1'

```

Creating the /home/sl236442/.soma-workflow/transfered_files directory fixes the problem, but it should be done automatically
(moreover the client-side error in soma_workflow_gui doesn't display the full error)

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Li, Jinpeng** (Li, Jinpeng)
Original Date: 2014-01-10T11:23:06Z

---

I have added a function to create configuration directories in configuration.py when start the engine and the database. Now it should work.
