### ISSUE TITLE
When soma application fails to load plugins, the exception is not displayed correctly

### ISSUE THREAD

**Issue by denisri** [brainvisa/testbidon#278]
---

Author Name: **Souedet, Nicolas** (Souedet, Nicolas)
Original Redmine Issue: 9825, https://bioproj.extra.cea.fr/redmine/issues/9825
Original Date: 2014-04-04
Original Assignee: Souedet, Nicolas

---

Error is displayed as follow :
```
Traceback (most recent call last):                                                                                                                                                                
  File "<string>", line 27, in <module>                                                                                                                                                           
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-release/brainvisa/neuro.py", line 251, in <module>                                         
    soma_app.initialize()
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-release/python/soma/application.py", line 120, in initialize
    module = self.load_plugin_module( plugin_module )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-release/python/soma/application.py", line 163, in load_plugin_module                       
    traceback.print_last()                                                                                                                                                                        
  File "/usr/lib/python2.6/traceback.py", line 246, in print_last                                                                                                                                 
    print_exception(sys.last_type, sys.last_value, sys.last_traceback,                                                                                                                            
AttributeError: 'module' object has no attribute 'last_type'

```

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Souedet, Nicolas** (Souedet, Nicolas)
Original Date: 2014-04-04T12:00:00Z

---

Appliqué par commit r61736.
