### ISSUE TITLE
BrainVISA preferences edition fails (at least on Ubuntu 10.04 LTS)

### ISSUE THREAD

**Issue by denisri** [brainvisa/testbidon#284]
---

Author Name: **Souedet, Nicolas** (Souedet, Nicolas)
Original Redmine Issue: 10934, https://bioproj.extra.cea.fr/redmine/issues/10934
Original Date: 2014-09-01
Original Assignee: Souedet, Nicolas

---

The bug was introduced by r63320
Traceback (most recent call last):
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/brainvisa/configuration/qt4gui/neuroConfigGUI.py", line 63, in editConfiguration
    if appGUI.edit( configuration, live=False, modal=True ):
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/soma/qt4gui/automatic.py", line 189, in edit
    dialog = self.createEditionDialog( object, parent=parent, live=live, modal=modal )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/soma/qt4gui/automatic.py", line 176, in createEditionDialog
    return EditionDialog( object, parent=parent, name=name, live=live, modal=modal, wflags=wflags )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/soma/qt4gui/automatic.py", line 122, in __init__
    self.__widget = self.__qtgui.editionWidget( object, parent=None, live=live )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/soma/qt4gui/configuration_qt4gui.py", line 247, in editionWidget
    live=live )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/brainvisa/configuration/qt4gui/spm_configuration_qt4gui.py", line 60, in editionWidget
    self._defaultWidget = self._defaultGUI.editionWidget( value, parent=widget, live=True )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/soma/signature/qt4gui/signature_qt4gui.py", line 280, in editionWidget
    return HasSignatureEditionWidget( self, object, parent, name, live )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/soma/signature/qt4gui/signature_qt4gui.py", line 111, in __init__
    self._createSignatureWidgets( object, live )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/soma/signature/qt4gui/signature_qt4gui.py", line 150, in _createSignatureWidgets
    live=live )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/soma/signature/qt4gui/fileName_qt4gui.py", line 57, in editionWidget
    self._lineEdit = TimeredQLineEdit( )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/soma/qt4gui/timered_widgets.py", line 171, in __init__
    timerInterval=timerInterval )
  File "/volatile/ns215310/development/svn/brainvisa_bioproj/brainvisa/build-trunk-Ubuntu-10.04-x86_64-debug/python/soma/qt4gui/timered_widgets.py", line 86, in __init__
    self.qLineEdit.lostFocus.connect(self._noMoreUserModification)
AttributeError: 'TimeredQLineEdit' object has no attribute 'lostFocus'

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Souedet, Nicolas** (Souedet, Nicolas)
Original Date: 2014-09-01T14:05:42Z

---

Appliqué par commit brainvisa:r63391.
