### ISSUE TITLE
Error when installing soma-base with pip

### ISSUE THREAD

**Issue by denisri** [brainvisa/testbidon#316]
---

Author Name: **Cointepas, Yann** (Cointepas, Yann)
Original Redmine Issue: 14625, https://bioproj.extra.cea.fr/redmine/issues/14625
Original Date: 2016-03-29
Original Assignee: Cointepas, Yann

---

The setup.py script uses a ez_setup module that is not installed. This lead to an error when installing a new virtualenv (see below). As far as I know, this import is useless for installing with @pip@. Therefore I will remove it an make a new package on Pypi (without changing version).

```
virtualenv /tmp/venv
/tmp/venv/bin/pip install soma-base
Downloading/unpacking soma-base
  Downloading soma-base-4.5.7.tar.gz (148kB): 148kB downloaded
  Running setup.py (path:/tmp/venv/build/soma-base/setup.py) egg_info for package soma-base
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/venv/build/soma-base/setup.py", line 3, in <module>
        from ez_setup import use_setuptools
    ImportError: No module named ez_setup
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/venv/build/soma-base/setup.py", line 3, in <module>

    from ez_setup import use_setuptools

ImportError: No module named ez_setup

```

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Cointepas, Yann** (Cointepas, Yann)
Original Date: 2016-03-29T11:00:11Z

---

Appliqué par commit brainvisa:r72381.
