### ISSUE TITLE
Windows: soma_workflow_gui error when no workflow is submitted and the plot view is refreshed

### ISSUE THREAD

**Issue by denisri** [brainvisa/testbidon#326]
---

Author Name: **Souedet, Nicolas** (Souedet, Nicolas)
Original Redmine Issue: 16345, https://bioproj.extra.cea.fr/redmine/issues/16345
Original Date: 2017-03-07
Original Assignee: Souedet, Nicolas

---

The error occurs only on windows system. To reproduce it, open a workflow file but do not submit it.
Then click on the refresh button:
```
Traceback (most recent call last):
  File "D:\python\soma_workflow\gui\workflowGui.py", line 3242, in refresh
    self.dataChanged(force=True)
  File "D:\python\soma_workflow\gui\workflowGui.py", line 3251, in dataChanged
    self.rebuild_graph()
  File "D:\python\soma_workflow\gui\workflowGui.py", line 3257, in rebuild_graph
    image_file_path = self.printWorkflow()
  File "D:\python\soma_workflow\gui\workflowGui.py", line 3359, in printWorkflow
    subprocess.check_call(command)
  File "Z:\i2bm\brainvisa\Windows-7-i686\python\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "Z:\i2bm\brainvisa\Windows-7-i686\python\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "Z:\i2bm\brainvisa\Windows-7-i686\python\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "Z:\i2bm\brainvisa\Windows-7-i686\python\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] File not found

```

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Souedet, Nicolas** (Souedet, Nicolas)
Original Date: 2017-03-09T09:39:57Z

---

Error was fixed by commit https://github.com/neurospin/soma-workflow/commit/860ca89fd013af140e7f026b040ad52110c24627 but we need to cross compile and package dot as described in #16356.
