### ISSUE TITLE
dicom writer crashes on CentOS 5.11

### ISSUE THREAD

**Issue by denisri** [brainvisa/testbidon#328]
---

Author Name: **Riviere, Denis** (Riviere, Denis)
Original Redmine Issue: 17298, https://bioproj.extra.cea.fr/redmine/issues/17298
Original Date: 2017-09-07

---

aims.write() segfaults on our cluster gabriel (CentOS 5.11)
The following code reproduces the problem:
```
from soma import aims
vol = aims.read('/neurospin/brainvisa/tests/Ubuntu-14.04-x86_64/ref/bug_fix/test_morphologist_pipeline/data_for_anatomist/subject01/subject01.nii')
aims.write(vol, '/tmp/vol_test.dcm')

```

gdb backtrace:
```
(gdb) bt
#0  0x00002b67283f926b in DcmFileFormat::checkValue(DcmMetaInfo*, DcmDataset*, DcmTagKey const&, DcmObject*, E_TransferSyntax) () from /i2bm/brainvisa/CentOS-5.11-x86_64/dcmtk/lib64/libdcmdata.so
#1  0x00002b67283f9fcb in DcmFileFormat::validateMetaInfo(E_TransferSyntax) () from /i2bm/brainvisa/CentOS-5.11-x86_64/dcmtk/lib64/libdcmdata.so
#2  0x00002b67283f86e1 in DcmFileFormat::write(DcmOutputStream&, E_TransferSyntax, E_EncodingType, E_GrpLenEncoding, E_PaddingEncoding, unsigned int, unsigned int, unsigned int) () from /i2bm/brainvisa/CentOS-5.11-x86_64/dcmtk/lib64/libdcmdata.so
#3  0x00002b67283f7ee0 in DcmFileFormat::saveFile(char const*, E_TransferSyntax, E_EncodingType, E_GrpLenEncoding, E_PaddingEncoding, unsigned int, unsigned int, bool) () from /i2bm/brainvisa/CentOS-5.11-x86_64/dcmtk/lib64/libdcmdata.so
#4  0x00002b6727cbe9d5 in dcm::SCImageStorageWriter::writeDatasets(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dcm::DicomProxy&) ()
   from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libsomadicom.so.4.6.0
#5  0x00002b6727c99781 in dcm::DicomWriter::write(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dcm::DicomProxy&) () from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libsomadicom.so.4.6.0
#6  0x00002b6727c9a9b2 in dcm::DicomWriterFactory::write(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dcm::DicomProxy&, bool) () from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libsomadicom.so.4.6.0
#7  0x00002b6727c8fe1d in dcm::DicomIO::write(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dcm::DicomProxy&, bool) () from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libsomadicom.so.4.6.0
#8  0x00002b6727ccca61 in carto::DicomImageWriter<short>::write(short const*, carto::DataSourceInfo&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<long, std::allocator<long> > const&, carto::Object) ()
   from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libsomadicom.so.4.6.0
#9  0x00002b66f3b80806 in carto::VolumeFormatWriter<short>::write(carto::Volume<short> const&, carto::rc_ptr<carto::DataSourceInfo>, carto::Object) () from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libcartodata.so.4.6.0
#10 0x00002b66f3b06b91 in carto::Writer<carto::Volume<short> >::write(carto::Volume<short> const&, carto::Object, int, int) () from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libcartodata.so.4.6.0
#11 0x00002b66f2033520 in aims::Writer<carto::Volume<short> >::write(carto::Volume<short> const&, bool, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const*) () from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/lib/libaimsdata.so.4.6.0
#12 0x00002b66ef16849d in meth_Writer_Volume_S16_write () from /neurospin/brainvisa/build/CentOS-5.11-x86_64/bug_fix/python/soma/aims/aimssip.so
#13 0x00002b66e64bb259 in call_function (f=0xac502a0, throwflag=<value optimized out>) at Python/ceval.c:4021
#14 PyEval_EvalFrameEx (f=0xac502a0, throwflag=<value optimized out>) at Python/ceval.c:2666
#15 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x9d4f930, globals=<value optimized out>, locals=<value optimized out>, args=0x5, argcount=3, kws=0xac53818, kwcount=2, defs=0xaafb650, defcount=2, closure=0x0) at Python/ceval.c:3253
#16 0x00002b66e64ba915 in call_function (f=0xac53660, throwflag=<value optimized out>) at Python/ceval.c:4117
#17 PyEval_EvalFrameEx (f=0xac53660, throwflag=<value optimized out>) at Python/ceval.c:2666
#18 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x9d4fc30, globals=<value optimized out>, locals=<value optimized out>, args=0x4, argcount=2, kws=0xab3fd90, kwcount=0, defs=0xaafb698, defcount=2, closure=0x0) at Python/ceval.c:3253
#19 0x00002b66e64ba915 in call_function (f=0xab3fc00, throwflag=<value optimized out>) at Python/ceval.c:4117
#20 PyEval_EvalFrameEx (f=0xab3fc00, throwflag=<value optimized out>) at Python/ceval.c:2666
#21 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x9af3a30, globals=<value optimized out>, locals=<value optimized out>, args=0x0, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3253
#22 0x00002b66e64bcbe2 in PyEval_EvalCode (co=0x0, globals=0x1, locals=0x7fff9de4ade8) at Python/ceval.c:667
#23 0x00002b66e64bbe6a in exec_statement (f=0x9b1fe20, throwflag=<value optimized out>) at Python/ceval.c:4718
#24 PyEval_EvalFrameEx (f=0x9b1fe20, throwflag=<value optimized out>) at Python/ceval.c:1880
#25 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x9661030, globals=<value optimized out>, locals=<value optimized out>, args=0x9b309a8, argcount=2, kws=0x9b309b8, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3253
#26 0x00002b66e64ba915 in call_function (f=0x9b307d0, throwflag=<value optimized out>) at Python/ceval.c:4117
#27 PyEval_EvalFrameEx (f=0x9b307d0, throwflag=<value optimized out>) at Python/ceval.c:2666
#28 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x965df30, globals=<value optimized out>, locals=<value optimized out>, args=0x4, argcount=3, kws=0x9c96658, kwcount=1, defs=0x97eeda8, defcount=1, closure=0x0) at Python/ceval.c:3253
#29 0x00002b66e64ba915 in call_function (f=0x9c96450, throwflag=<value optimized out>) at Python/ceval.c:4117
#30 PyEval_EvalFrameEx (f=0x9c96450, throwflag=<value optimized out>) at Python/ceval.c:2666
#31 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x965deb0, globals=<value optimized out>, locals=<value optimized out>, args=0x4, argcount=2, kws=0x9bc21a0, kwcount=1, defs=0x9756f08, defcount=2, closure=0x0) at Python/ceval.c:3253
#32 0x00002b66e64ba915 in call_function (f=0x9bc1fe0, throwflag=<value optimized out>) at Python/ceval.c:4117
#33 PyEval_EvalFrameEx (f=0x9bc1fe0, throwflag=<value optimized out>) at Python/ceval.c:2666
#34 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x96450b0, globals=<value optimized out>, locals=<value optimized out>, args=0x2, argcount=1, kws=0x9a20428, kwcount=1, defs=0x9646568, defcount=1, closure=0x0) at Python/ceval.c:3253
#35 0x00002b66e64ba915 in call_function (f=0x9a20290, throwflag=<value optimized out>) at Python/ceval.c:4117
#36 PyEval_EvalFrameEx (f=0x9a20290, throwflag=<value optimized out>) at Python/ceval.c:2666
#37 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x95f2f30, globals=<value optimized out>, locals=<value optimized out>, args=0x2, argcount=1, kws=0x9a0f568, kwcount=0, defs=0x9646528, defcount=1, closure=0x0) at Python/ceval.c:3253
#38 0x00002b66e64ba915 in call_function (f=0x9a0f3e0, throwflag=<value optimized out>) at Python/ceval.c:4117
#39 PyEval_EvalFrameEx (f=0x9a0f3e0, throwflag=<value optimized out>) at Python/ceval.c:2666
#40 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x986a030, globals=<value optimized out>, locals=<value optimized out>, args=0x9a05f30, argcount=1, kws=0x9a05f38, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3253
#41 0x00002b66e64ba915 in call_function (f=0x9a05db0, throwflag=<value optimized out>) at Python/ceval.c:4117
#42 PyEval_EvalFrameEx (f=0x9a05db0, throwflag=<value optimized out>) at Python/ceval.c:2666
#43 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x986a230, globals=<value optimized out>, locals=<value optimized out>, args=0x0, argcount=0, kws=0x91f6630, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3253
#44 0x00002b66e64ba915 in call_function (f=0x91f64b0, throwflag=<value optimized out>) at Python/ceval.c:4117
#45 PyEval_EvalFrameEx (f=0x91f64b0, throwflag=<value optimized out>) at Python/ceval.c:2666
#46 0x00002b66e64bcb69 in PyEval_EvalCodeEx (co=0x2b66e68d58b0, globals=<value optimized out>, locals=<value optimized out>, args=0x0, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3253
#47 0x00002b66e64bcbe2 in PyEval_EvalCode (co=0x0, globals=0x1, locals=0x7fff9de4ade8) at Python/ceval.c:667
#48 0x00002b66e64e0301 in run_mod (fp=0x91cf030, filename=0x7fff9de521e1 "/i2bm/brainvisa/CentOS-5.11-x86_64/bin/ipython", start=<value optimized out>, globals=0x916e270, locals=0x916e270, closeit=1, flags=0x7fff9de50cd0) at Python/pythonrun.c:1353
#49 PyRun_FileExFlags (fp=0x91cf030, filename=0x7fff9de521e1 "/i2bm/brainvisa/CentOS-5.11-x86_64/bin/ipython", start=<value optimized out>, globals=0x916e270, locals=0x916e270, closeit=1, flags=0x7fff9de50cd0) at Python/pythonrun.c:1339
#50 0x00002b66e64e05c4 in PyRun_SimpleFileExFlags (fp=<value optimized out>, filename=0x7fff9de521e1 "/i2bm/brainvisa/CentOS-5.11-x86_64/bin/ipython", closeit=1, flags=0x7fff9de50cd0) at Python/pythonrun.c:943
#51 0x00002b66e64f2caa in Py_Main (argc=<value optimized out>, argv=0x7fff9de50df8) at Modules/main.c:639
#52 0x000000372361d9f4 in __libc_start_main () from /lib64/libc.so.6
#53 0x0000000000400629 in _start ()

```

I don't know it it is a problem of version of dcmtk on this system, which is an old 3.5.4

**Comment by denisri** [comment]
---

Original Redmine Comment
Author Name: **Poupon, Fabrice** (Poupon, Fabrice)
Original Date: 2017-10-05T08:10:10Z

---

Appliqué par commit brainvisa:r79321.
